"""atualiza_usuario

Revision ID: 88007349700a
Revises: e3830a282a7d
Create Date: 2026-08-08 22:05:07.425258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88007349700a'
down_revision: Union[str, Sequence[str], None] = 'e3830a282a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('foto_url', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('ativo', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_usuario_google_id'), 'usuario', ['google_id'], unique=True)
    op.drop_column('usuario', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usuario_google_id'), table_name='usuario')
    op.drop_column('usuario', 'ativo')
    op.drop_column('usuario', 'foto_url')
    op.drop_column('usuario', 'google_id')
    # ### end Alembic commands ###
