"""banco_inicial_limpo_de_verdade

Revision ID: e3830a282a7d
Revises: 
Create Date: 2026-08-02 17:15:17.090271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3830a282a7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('margem_lucro', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('segmento_marketing', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('unidade',
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_unidade')
    )
    op.create_table('produto',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo_barras', sa.String(), nullable=True),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id_unidade'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=True)
    op.create_index(op.f('ix_usuario_login'), 'usuario', ['login'], unique=True)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=True)
    op.create_table('venda',
    sa.Column('id_venda', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('forma_pagamento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id_unidade'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_venda')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda')
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_login'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('produto')
    op.drop_table('unidade')
    op.drop_table('cliente')
    op.drop_table('categoria')
    # ### end Alembic commands ###
